{% set name = "legacy-suitcase" %}
{% set version = "0.9.1" %}
{% set sha256 = "dd878b9d704825114a42ae2c6a4d680cf37e83f37c8ce787db1819780cac0071" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bluesky/suitcase-core/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - databroker
    - h5py
    - numpy

test:
  imports:
    - suitcase
    - suitcase.hdf5

about:
  home: https://github.com/bluesky/suitcase-core
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Legacy HDF5 exporter used at NSLS-II ESM-1 and ESM-2
  dev_url: https://github.com/bluesky/suitcase-core
  doc_url: https://blueskyproject.io/suitcase
